const defaultConfig = {
  spreadsheet: {
    sheetName: "",
    skipEmptyRows: true,
  },
  page: {
    size: "A4",
    orientation: "portrait",
    widthMm: 210,
    heightMm: 297,
    marginMm: 10,
    gapMm: 6,
  },
  layout: {
    columns: 2,
    rows: 5,
    centerOnPage: true,
  },
  card: {
    widthMm: 85.6,
    heightMm: 54,
    fillColor: "#FFFFFF",
    borderColor: "#D6D0C4",
    borderWidthMm: 0.35,
    background: {
      default: "",
      rules: [
        {
          field: "duty",
          equals: "Manager",
          background: "manager",
        },
        {
          field: "duty",
          equals: "Coach",
          background: "coach",
        },
      ],
    },
  },
  photos: {
    fields: ["name", "id"],
    placeholderLabel: "NO PHOTO",
  },
  elements: [
    {
      id: "photo",
      type: "photo",
      xMm: 6,
      yMm: 8,
      widthMm: 24,
      heightMm: 30,
      fit: "cover",
      borderColor: "#FFFFFF",
      borderWidthMm: 0.5,
      fillColor: "#F3F0EA",
    },
    {
      id: "name",
      type: "text",
      field: "name",
      xMm: 34,
      yMm: 11,
      widthMm: 46,
      heightMm: 12,
      font: "Helvetica-Bold",
      fontSize: 14,
      minFontSize: 10,
      color: "#111111",
      align: "left",
      valign: "top",
      lineHeight: 1.1,
      uppercase: true,
    },
    {
      id: "duty",
      type: "text",
      field: "duty",
      xMm: 34,
      yMm: 25,
      widthMm: 46,
      heightMm: 9,
      font: "Helvetica",
      fontSize: 10,
      minFontSize: 8,
      color: "#405366",
      align: "left",
      valign: "top",
      lineHeight: 1.15,
    },
    {
      id: "id",
      type: "text",
      field: "id",
      prefix: "ID: ",
      xMm: 34,
      yMm: 37,
      widthMm: 40,
      heightMm: 8,
      font: "Helvetica-Bold",
      fontSize: 9,
      minFontSize: 8,
      color: "#111111",
      align: "left",
      valign: "top",
      lineHeight: 1.15,
    },
  ],
};

module.exports = {
  defaultConfig,
};

